default_language_version:
  # default language version for each language used in the repository
  python: python3.9
repos:
  - repo: https://github.com/pycqa/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [ '-iii', '-ll' ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
        ]
  - repo: https://github.com/pycqa/pylint
    rev: "pylint-2.7.2"
    hooks:
      - id: pylint
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        # args: [ "--load-plugins=pylint_django", "--django-settings-module=app.settings" ]
        additional_dependencies: [
          # pylint dependency
          # pylint_django,
          # runtime dependencies
          # ....
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
      - id: mypy
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
