version: '3'

services:

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.7
    ports:
      - 16686:16686

  auth:
    container_name: auth
    image: auth
    build: ./auth
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
    expose:
      - 5001
    entrypoint: >
      sh -c " python wait_for_postgres.py
      && gunicorn wsgi_app:app -b 0.0.0.0:5001 -w 2 --log-level debug --timeout 0"
    restart: always 
    
      
  db:
    image: postgres:13-alpine
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data/
    container_name: db
    env_file:
      - ./.env
    expose:
      - 5432  
    ports:
      - 5432:5432    
      
  redis:
    image: redis:7.0.3
    volumes: 
      - redis_data:/data
    container_name: redis
    env_file:
      - ./.env
    expose:
      - 6379
    ports:
      - 6379:6379    
      
  nginx:
    container_name: nginx
    image: nginx:1.23.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    depends_on:
      - auth
      
volumes:
  redis_data:

